from __future__ import annotations

from pathlib import Path

from .cache import build_cache_key, build_cache_namespace
from .config import (
    BENCHMARK_COMMAND,
    DEFAULT_CACHE_TTL,
    DEFAULT_CHROMA_DIR,
    DEFAULT_CHUNK_OVERLAP,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_DOCS_DIR,
    DEFAULT_EMBEDDING_MODEL,
    DEFAULT_LLM_MODEL,
    DEFAULT_OLLAMA_BASE_URL,
    DEFAULT_PROMPT_PATH,
    DEFAULT_REDIS_URL,
    DEFAULT_TOP_K,
    EVALS_COMMAND,
    HEALTHCHECK_COMMAND,
    AppConfig,
    ConfigError,
    INGEST_COMMAND,
    load_config,
)
from .catalog import CATALOG_FILENAME, CATALOG_VERSION, CorpusCatalog, DocumentRecord, build_document_record, catalog_file, read_catalog, write_catalog
from .documents import (
    SUPPORTED_DOCUMENT_SUFFIXES,
    format_docs,
    get_docs_fingerprint,
    list_document_paths,
    list_pdf_paths,
    load_all_documents,
    load_all_pdfs,
    split_documents,
)
from .health import HealthCheck, HealthReport, build_health_report, format_health_report
from .indexing import (
    IngestError,
    IngestResult,
    RuntimeValidation,
    build_chroma_store,
    create_embeddings,
    create_llm,
    create_temp_build_directory,
    has_index_artifacts,
    index_matches_fingerprint,
    ingest_corpus,
    marker_file,
    open_vectorstore,
    read_index_fingerprint,
    replace_index_directory,
    validate_runtime_readiness,
)
from .prompts import PromptError, build_prompt, load_prompt_text
from .runtime import Citation, QueryResult, build_citations, render_answer, render_citations
from .telemetry import log_event

try:
    SYSTEM_PROMPT_TEXT = load_prompt_text(Path(DEFAULT_PROMPT_PATH))
except PromptError:
    SYSTEM_PROMPT_TEXT = ""

__all__ = [
    "AppConfig",
    "BENCHMARK_COMMAND",
    "CATALOG_FILENAME",
    "CATALOG_VERSION",
    "Citation",
    "ConfigError",
    "DEFAULT_CACHE_TTL",
    "DEFAULT_CHROMA_DIR",
    "DEFAULT_CHUNK_OVERLAP",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_DOCS_DIR",
    "DEFAULT_EMBEDDING_MODEL",
    "DEFAULT_LLM_MODEL",
    "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_PROMPT_PATH",
    "DEFAULT_REDIS_URL",
    "DEFAULT_TOP_K",
    "DocumentRecord",
    "CorpusCatalog",
    "EVALS_COMMAND",
    "HEALTHCHECK_COMMAND",
    "HealthCheck",
    "HealthReport",
    "INGEST_COMMAND",
    "IngestError",
    "IngestResult",
    "PromptError",
    "RuntimeValidation",
    "SUPPORTED_DOCUMENT_SUFFIXES",
    "SYSTEM_PROMPT_TEXT",
    "build_cache_key",
    "build_cache_namespace",
    "build_citations",
    "build_chroma_store",
    "build_document_record",
    "build_health_report",
    "build_prompt",
    "catalog_file",
    "create_embeddings",
    "create_llm",
    "create_temp_build_directory",
    "format_docs",
    "format_health_report",
    "get_docs_fingerprint",
    "has_index_artifacts",
    "index_matches_fingerprint",
    "ingest_corpus",
    "list_document_paths",
    "list_pdf_paths",
    "load_all_documents",
    "load_all_pdfs",
    "load_config",
    "load_prompt_text",
    "log_event",
    "marker_file",
    "open_vectorstore",
    "QueryResult",
    "read_index_fingerprint",
    "read_catalog",
    "render_answer",
    "render_citations",
    "replace_index_directory",
    "split_documents",
    "validate_runtime_readiness",
    "write_catalog",
]
